### ISSUE TITLE
Error when activated with Disqus plugin

### ISSUE THREAD

**Issue by ddrager** [shawfactor/lh-archived-post-status#1]
When trying to archive a page via the "Archive" button on the listing of pages, received a 500 server error. 

```PHP Fatal error:  Uncaught Error: Call to a member function get_page_permastruct() on null in /home/tcbasic/domains/tcbasic.com/public_html/wp-includes/link-template.php:357
Stack trace:
#0 /wp-includes/link-template.php(320): _get_page_link(Object(WP_Post), false, false)
#1 /wp-includes/link-template.php(144): get_page_link(Object(WP_Post), false, false)
#2 /wp-content/plugins/disqus-comment-system/disqus.php(1243): get_permalink(Object(WP_Post))
...
```

Was able to be fixed by deactivating Disqus, however I require Disqus - plus it is likely this issue will impact compatibility with other plugins as well. 

I have a fix coming shortly. Thanks.

**Comment by ddrager** [comment]
Looks like this Github version is not updated to release version on Wordpress.org.

To fixed, I added the following line to the top of `private function archive_post_by_id`:

```$GLOBALS['wp_rewrite'] = new wp_rewrite;```

Hope this helps anyone else looking at this error!

**Comment by ddrager** [comment]
Closing as repo is out of date.
